esphome:
  name: esphymer
  friendly_name: EspHymer

esp32:
  board: esp32-c3-devkitm-1

  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "g7Md1bzfJrRLDf3NdJpODAljdNggVf3OIzD0/pp58cE="

ota:
  - platform: esphome
    password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphymer Fallback Hotspot"
    password: !secret ap_pwd

captive_portal:


external_components:
  - source: github://Fabian-Schmidt/esphome-truma_inetbox
    components: ["truma_inetbox"]

uart:
  - id: lin_uart_bus
    tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 9600
    stop_bits: 2

truma_inetbox:
  uart_id: lin_uart_bus

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  id: bus_a

one_wire:
  - platform: gpio
    pin: GPIO10
    id: bus_b

switch:
  - platform: template
    name: Parking
    id: switch1
    optimistic: true
    lambda: return id(switch1).state;

  - platform: gpio
    pin: GPIO6
    name: "Phone Charger"
    inverted: true

binary_sensor:
  - platform: gpio
    pin: GPIO7
    name: "PIR Sensor"
    device_class: motion

  - platform: truma_inetbox
    name: "CP Plus alive"
    type: CP_PLUS_CONNECTED

sensor:
  - platform: truma_inetbox
    name: "Current Room Temperature"
    type: CURRENT_ROOM_TEMPERATURE
  - platform: truma_inetbox
    name: "Current Water Temperature"
    type: CURRENT_WATER_TEMPERATURE
  - platform: truma_inetbox
    name: "Target Room Temperature"
    type: TARGET_ROOM_TEMPERATURE
  - platform: truma_inetbox
    name: "Target Water Temperature"
    type: TARGET_WATER_TEMPERATURE

  - platform: bme280_i2c
    i2c_id: bus_a
    address: 0x76
    temperature:
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"

  - platform: dallas_temp
    one_wire_id: bus_b
    address: 0x8b3c01f095401e28
    name: "T1"
    unit_of_measurement: "°C"

  - platform: dallas_temp
    one_wire_id: bus_b
    address: 0xa83c01f095b01928
    name: "T2"
    unit_of_measurement: "°C"

  - platform: dallas_temp
    one_wire_id: bus_b
    address: 0xdb3c01f0952a3328
    name: "T3"
    unit_of_measurement: "°C"

  - platform: mpu6050
    address: 0x68
    i2c_id: bus_a
    accel_x:
      id: accel_x
      name: "MPU6050 Accel X"
      filters:
       - sliding_window_moving_average:
          window_size: 10
          send_every: 5
       - offset: 1.0
    accel_y:
      id: accel_y
      name: "MPU6050 Accel Y"
      filters:
       - sliding_window_moving_average:
          window_size: 10
          send_every: 5
       - offset: -6.4
    accel_z:
      id: accel_z
      name: "MPU6050 Accel z"
      filters:
       - sliding_window_moving_average:
          window_size: 10
          send_every: 5
       - offset: -7.4
    gyro_x:
      name: "MPU6050 Gyro X"
      id: gyro_x
      filters:
       - sliding_window_moving_average:
          window_size: 10
          send_every: 5
    gyro_y:
      name: "MPU6050 Gyro Y"
      id: gyro_y
      filters:
       - sliding_window_moving_average:
          window_size: 10
          send_every: 5
    gyro_z:
      name: "MPU6050 Gyro z"
      id: gyro_z
      filters:
       - sliding_window_moving_average:
          window_size: 10
          send_every: 5
    temperature:
      name: "MPU6050 Temperature"
      filters:
       - sliding_window_moving_average:
          window_size: 10
          send_every: 10
    update_interval: 2s
    id: accel

  - platform: template
    id: roll
    name: roll
    accuracy_decimals: 3
    lambda: |-
      return  (atan( id(accel_y).state / sqrt( pow( id(accel_x).state , 2) + pow( id(accel_z).state , 2) ) ) * 180 / PI) ;
    update_interval: 200ms
    unit_of_measurement: "°"

  - platform: template
    id: pitch
    name: pitch
    accuracy_decimals: 3
    lambda: |-
      return  (atan(-1 * id(accel_x).state / sqrt(pow(id(accel_y).state, 2) + pow(id(accel_z).state, 2))) * 180 / PI);
    update_interval: 200ms
    unit_of_measurement: "°"

  - platform: template
    id: angleX
    name: angleX
    accuracy_decimals: 3
    lambda: |-
      return  (asin(id(accel_x).state / 9.81) * 180 / PI) * -1;
    update_interval: 200ms
    unit_of_measurement: "°"

  - platform: template
    id: angleY
    name: angleY
    accuracy_decimals: 3
    lambda: |-
      return  (asin(id(accel_y).state / 9.81) * 180 / PI) * -1;
    update_interval: 200ms
    unit_of_measurement: "°"

interval:
  - interval: 200ms
    then:
      - if:
          condition:
            - switch.is_on: switch1
          then:
            - component.update: accel